### PR TITLE
feat: fix various minor issues & improve inferring

### LINKED ISSUE #272: Add support for "typeof" inference
No typescript type inference??

https://deno.land/x/masx200_cloudflare_api_dns_record_zone@1.0.0/NS-Record.ts

https://doc.deno.land/https://deno.land/x/masx200_cloudflare_api_dns_record_zone@1.0.0/mod.ts/~/NSRecord

https://www.typescriptlang.org/zh/play?#code/KYDwDg9gTgLgBDAnmYcByBlASsAxtAEzgF4FlgIAzOAOwGcB9KPQgbgCh9756mWoipAN7s4YuACIAlgQkAuSQGYA7ACZgANmUBOAKwAWAAyrdwQwCMAhhsu2NBXQA4N57WfO7tEgDSjxEpBR5SUwJOEs6OC46GF9xSRpLAFtgYIlQZLAAG2AAOnwknz8xCS4YYBoYNPoARlyMpOy8gqL4iTAoCBApS3Mc4JgoAFdgOP8OrqlgWQVKSyy6UeLJGBgs4MUNQ0MxkqyIXABraeC5haW2gC8IGmAGGTTjRWAaw11KfTxgSkdLAm1cJZFDVLI4VKoCIZcIpdIpWv5rrcGIkUmkGk18hBCrtJLhmJZygQGDc0qpDDV9ABacnUmoAFTecjJcm2uRqqkU+l0AC14SUkhACFJKFMiSSFBIyRTabSGbomYYWYY2RyubycRICATLMEhABfDUpGA6hQieJtSxDGAQBh-AgnBSDEY4tp0CBDKC4VISjpSJKWKCIPlwA3sPWsIA

input

```ts
export type NSRecord = typeof ns_record;
const ns_record = {
    "id": "372e67954025e0ba6aaa6d586b9e0b59",
    "type": "NS" as const,
    "name": "example.com",
    "content": "ns1.example.com",
    "proxiable": true,
    "proxied": false,
    "ttl": 3600,
    "locked": false,
    "zone_id": "023e105f4ecef8ad9ca31a8372d0c353",
    "zone_name": "example.com",
    "created_on": "2014-01-01T05:20:00.12345Z",
    "modified_on": "2014-01-01T05:20:00.12345Z",
    "data": {},
    "meta": {
        "auto_added": true,
        "source": "primary",
    },
};

```
output expected
```ts
export declare type NSRecord = typeof ns_record;
declare const ns_record: {
    id: string;
    type: "NS";
    name: string;
    content: string;
    proxiable: boolean;
    proxied: boolean;
    ttl: number;
    locked: boolean;
    zone_id: string;
    zone_name: string;
    created_on: string;
    modified_on: string;
    data: {};
    meta: {
        auto_added: boolean;
        source: string;
    };
};
export {};
```

image

### LINKED ISSUE #296: Usage of `satisfies` type operator.
TypeScript 4.9 will introduce the `satisfies` type operator (see: https://devblogs.microsoft.com/typescript/announcing-typescript-4-9-beta/#the-satisfies-operator).  We need to make sure we handle it properly.  Mainly it will only come into play with type inference.

```ts
type Colors = "red" | "green" | "blue";

// Ensure that we have exactly the keys from 'Colors'.
const favoriteColors = {
    "red": "yes",
    "green": false,
    "blue": "kinda",
    "platypus": false
//  ~~~~~~~~~~ error - "platypus" was never listed in 'Colors'.
} satisfies Record<Colors, unknown>;

const g: boolean = favoriteColors.green;
```

### LINKED ISSUE #347: Add a mechanism to document type parameters
Currently deno doc indicates that a JS entity has type parameters and what their names are. However, it does not have a mechanism to add a text description of the type parameter's. TSDoc accomplishes this with  [`@typeParam`](https://tsdoc.org/pages/tags/typeparam/), and it would be awesome to have the same capability with `deno_doc`

### PR DESCRIPTION
**Pull request by crowlKats**
Closes #347 
Closes #272 
Closes #296

### CODE REVIEW

File: src/ts_type.rs [hunk 1]
```diff
@@ -1380,7 +1380,130 @@ pub fn infer_ts_type_from_expr(
...
-    _ => None,
+    Expr::TsSatisfies(satisfies) => {
+      // e.g.) const value = {foo: "bar"} satifies Record<string, string>;
+      infer_ts_type_from_expr(parsed_source, &satisfies.expr, is_const)
+    }
+    Expr::Update(_) => {
+      // e.g.) let foo = 0;
+      //       const bar = foo++;
+
+      // TODO: does not support bigints, needs type tracing
```
Comment (crowlKats) [inline src/ts_type.rs:1391]: not sure how ideal this is, but i think its fine

**Review by dsherret — APPROVED** [review]
Great!
